version: '3.4'

networks:
  cors_dev:
    external: true
  coreshop_next:
    external: false

services:
  db:
    image: mysql:8
    container_name: coreshop-next
    networks:
      - cors_dev
      - coreshop_next
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci]
    ports:
      - "3306:3306"
    volumes:
      - coreshop-next:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  nginx:
    image: nginx:stable-alpine
    container_name: coreshop-next-nginx
    volumes:
      - .:/var/www/html:cached
      -  ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - php-debug
    networks:
      - cors_dev
      - coreshop_next
    labels:
      - traefik.enable=true
      - traefik.http.routers.coreshop_next.rule=Host(`coreshop-next.localhost`)
      - traefik.http.routers.coreshop_next.entrypoints=cors_dev
      - traefik.http.routers.coreshop_next.tls=true
      - traefik.http.services.coreshop_next.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev

  php:
    image: pimcore/pimcore:php8.2-latest
    container_name: coreshop-next-php
    networks:
      - coreshop_next
    environment:
      COMPOSER_HOME: /var/www/html
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached

  php-debug:
    image: pimcore/pimcore:php8.2-debug-latest
    container_name: coreshop-next-php-debug
    networks:
      - coreshop_next
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_TRIGGER: PHPSTORM
      COMPOSER_HOME: /var/www/html
      XDEBUG_HOST: 198.19.248.254

volumes:
  coreshop-next:
