CoreShop\Component\Payment\Model\PaymentProviderRuleTranslation:
    exclusion_policy: ALL
    xml_root_name: payment_provider_rule_translation
    properties:
        label:
            expose: true
            type: string
            groups: [Detailed]
