name: Docs
on:
  push:
    branches: [ '4.0' ]
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Setup and Generate
      run: | 
        cd docs
        npm install
        npm run build

    - name:  Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Upload Folder
      uses: 'google-github-actions/upload-cloud-storage@v0'
      if: github.ref == 'refs/heads/4.0'
      with:
        path: 'docs/build/'
        destination: 'cors-wolke-coreshop-docs/4.0.0'
        parent: false
