coreshop_admin_variant_attributes:
    path: /admin/variant/attributes
    defaults: { _controller: CoreShop\Bundle\VariantBundle\Controller\VariantController::getAttributesAction }
    options:
        expose: true

coreshop_admin_variant_generator:
    path: /admin/variant/generate
    defaults: { _controller: CoreShop\Bundle\VariantBundle\Controller\VariantController::generateVariantsAction }
    methods: [POST]
    options:
        expose: true